### ISSUE TITLE
erro ao tentar extrair tabelas

### ISSUE THREAD

**Issue by frohfroh** [rafaelgou/fipe-crawler#1]
Quando tento extrair tabelas, o seguinte erro acontece:
Recuperando tabelas para 09/2017...
PHP Warning:  file_get_contents(http://www.fipe.org.br/pt-br/indices/veiculos): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Unavailable
 in /home/frohfroh/fipe-crawler/src/Fipe/Crawler.php on line 82

                                   
  [InvalidArgumentException]       
  The current node list is empty.

**Comment by rafaelgou** [comment]
Olá!

Parece que o site da Fipe está fora do ar.

[]'s
