### ISSUE TITLE
Como isso funciona?

### ISSUE THREAD

**Issue by osmaircoelho** [rafaelgou/fipe-crawler#12]
Primeiramente Rafael parabéns.

**Sobre a versao web**

Gostaria de saber as linguagens front e back, pelo que vi foi angular, e php,

como eh compilado front que foi gerado o **js/app.js?**

em **src\fipe\Database** existe metodos que gravam no banco de dados `saveTabelas, saveMarcas, saveModelos, saveAnoModelos, saveVeiculos, saveVeiculoCompletos ...` resumindo são métodos que salva no banco as informações, mas pesquisei no sistema e ele não faz isso, estou com uma ideia de gravar as informações no banco com a versão web após gerar todos os dados.

porem quando eu gero os dados após a extração, aparece um erro mas sem nada de mensagens, aguem sabe o que eh?

![erro_appjs](https://user-images.githubusercontent.com/2856340/168278471-0286543a-a9ef-45da-b943-c64344f66275.jpg)
![Screenshot 2022-05-13 124010](https://user-images.githubusercontent.com/2856340/168278477-b38e536b-8669-413d-8ead-ef09eddcc7b8.jpg)

grato pela atencao!

**Comment by rafaelgou** [comment]
Olá, tudo bem?

Bem, considere que o frontend não tem manutenção há mais de 5 anos, e não há mais suporte para o Angular utilizado. Isto posto, utiliza o `bower` para o build.

Seguindo os passos em https://github.com/rafaelgou/fipe-crawler#configura%C3%A7%C3%A3o  você configura o banco para o PHP, e rodando os comandos no shell você vai popular o banco com as informações.

[]'s

**Comment by OsmairDev** [comment]
fiz isso mas deu erro, vou postar aqui quando eu tiver tempo obrigado pela respota.
