### ISSUE TITLE
Retornos nulos em getModelos()

### ISSUE THREAD

**Issue by camilomunhoz** [rafaelgou/fipe-crawler#13]
Olá! Ótimo trabalho, organizado e intuitivo.

Estou usando a CLI e a etapa de extrair **modelos** parece estar comprometida. De 559 registros, apenas 10 curiosamente entraram para o banco de dados. As demais extrações não foram efetuadas (retorno nulo):

```
Warning: foreach() argument must be of type array|object, null given in C:\wamp64\www\fipe-crawler\src\Fipe\Crawler.php on line 199
```

Alguma ideia da causa? Posso investigar e fazer uma PR se não.

---

Parâmetros: `2024 9 Moto`

**Comment by rafaelgou** [comment]
Olá, meu caro.

Não tenho atualizado/utilizado este projeto há alguns anos, fique à vontade de enviar um PR que de imediato faço o merge.

Grato!

**Comment by camilomunhoz** [comment]
Rodei mais duas vezes e a quantidade de registros extraídos com sucesso varia toda vez. Aparentemente é alguma inconsistência nas requests e/ou no meu ambiente.

[**WONTFIX**] Estou trabalhando em um script autoral em JS para o mesmo fim. Acredito que será mais proveitoso para a comunidade se eu me dedicar nisso.

Abraço!
