### ISSUE TITLE
Exportar código como pacote do composer

### ISSUE THREAD

**Issue by lgaitan** [rafaelgou/fipe-crawler#2]
Olá,

será que seria possível exportar o código no composer, permitindo instalar o pacote atraves do composer?

Seria um modo mais fácil de integrar com sistemas existentes.

Estou disposto a fazer as modificacoes necessarias

**Comment by rafaelgou** [comment]
Olá, @lgaitan.

Veja, o "core" reside em dois arquivos:

- `Crawler.php`: faz as requisições necessárias ao servidor da Fipe.
- `Database.php`: salva em banco de dados.

Os dois arquivos que fazem a interface com estes dois são:

- `ExtrairVeiculoCommand.php`: executa o Crawler com parâmetros passados e com os dados recuperados utliza Database para salvar.
- `CsvCommand.php`: pega os dados extraídos e salvos em banco de dados e exporta para CSV

Minha sugestão é: podes usar estes arquivos como base e criar uma versão enxuta, sem interface ou linha de comando, para uso "embutido" em sistemas, incluíndo então o `composer.json`.
