### ISSUE TITLE
Não está funcionando!

### ISSUE THREAD

**Issue by victorstsw** [rafaelgou/fipe-crawler#6]
Eu fiz a instalação clonando o repositório e fazendo a instalação via composer, depois de configurar os arquivos e o banco de dados executo o script e ele não faz nada, fica tentando carregar e não baixa nada. OBS: eu possuo um outro script que tbm realizava o download em php e por algum motivo parou de funcionar tbm, acredito que a fipe mudou algo ou bloqueou acesso externo a aplicação deles. uq será que houve? Obrigado!

**Comment by rafaelgou** [comment]
Olá,

Realmente a Fipe mudou os endpoints da API. Eu havia invalidado a ferramenta, para evitar frustrações como a sua. O colega @tancredoit realizou o ajuste e enviou um pull request já incluído. Você pode ver as alterações realizadas por ele aqui:

https://github.com/rafaelgou/fipe-crawler/pull/5/commits/d6c549b915d86874eedbe35335fcd6f4b7cc6a43

A princípio foram apenas alterações dos endpoints - o restante da lógica e o conteúdo retornado permanecem os mesmos. Se não conseguiu fazer funcionar aqui, poderia tentar atualizar os endpoints na ferramenta que estava usando, pode funcionar.

Estou trabalhando numa versão atualizada, mas sem prazo, pois não uso mais a ferramenta. 

[]'s
Rafael

**Comment by victorstsw** [comment]
Olá, entendi, muito legal, eu acabei de achar o erro aqui tbm, era o formato de dados, os endpoints são os mesmos que vc citou, porem sem o https, que tbm funciona! mais muito bom, me ajudou a achar o problema do script que eu tinha anteriormente e sempre usava! muito obrigado!
